### ISSUE TITLE
Change File permissions after upload

### ISSUE THREAD

**Issue by ezekielriva** [luan/carrierwave-ftp#39]
Background:
We've been working on a project where the owner gave us a private server via FTP to storage and serve documents and images

Issue:
We use this gem to upload the file perfectly, however We can't serve it due to permissions error.

Fix:
I wrote a quick fix to this. I call the `CHMOD` command and change the permissions according to the uploader/carrierwave config

**Comment by luan** [comment]
Closed by #40
